baseURL = "https://ebuchman.github.io/"
languageCode = "en-us"
title = "Easy There Entropy"

theme = "hyde-hyde"

disqusShortname = "ebuchman-blog"

[params]
  author = "ebuchman"
  #authorimage = "img/ebuchman-epicenter.png"
  authorimage = "img/zhuang-actin.png"

  copyright = "ebuchman"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = true

  relatedPosts = true
  mainSections = ["post"]

[[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 900
  url = "/about/"

[[menu.main]]
  name = "Media"
  identifier = "media"
  weight = 200
  url = "/media/"

      


[params.social]
  twitter = "buchmanster"
  github = "ebuchman"
  linkedin = "ethan-buchman-10b34944"
  keybase = "ebuchman"

